apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medical-app
  template:
    metadata:
      labels:
        app: medical-app
    spec:
      containers:
      - name: medical-app
        image: rajuprudhvi/medical_shop:605dce1fe67335cff863099f4c63e5a9121f1917
        ports:
        - containerPort: 80
