apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture-app
  template:
    metadata:
      labels:
        app: furniture-app
    spec:
      containers:
      - name: furniture-app
        image: rajuprudhvi/furniture_store:cb9172e4ce7456e72ccf702889a12643069b2c01
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: furniture-service
spec:
  type: NodePort
  selector:
    app: furniture-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010