# apiVersion: kustomize.toolkit.fluxcd.io/v1
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: school-app-ks
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/schoolapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
