apiVersion: apps/v1
kind: Deployment
metadata:
  name: coconut-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coconut-app
  template:
    metadata:
      labels:
        app: coconut-app
    spec:
      containers:
      - name: coconut-app
        image: rajuprudhvi/coconut_business:6d7998ce8c8ba57638c62c1fef341fc3d5366279
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: coconut-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: coconut-service
spec:
  type: NodePort
  selector:
    app: coconut-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
