apiVersion: v1
kind: Secret
metadata:
  name: coconut-db-secret
type: Opaque
data:
  # Base64 encoded values for PostgreSQL
  DB_HOST: cG9zdGdyZXM= # postgres
  DB_PORT: NTQzMg== # 5432
  DB_NAME: Y29jb251dF9kYg== # coconut_db
  DB_USER: Y29jb251dF91c2Vy # coconut_user
  DB_PASSWORD: cG9zdGdyZXNfcGFzcw== # postgres_pass